"""
expand_background_knowledge_v2.py
----------------------------------
Improved background expansion pipeline addressing:
  1. Context-anchored prompting  — source paragraph travels with the concept,
     constraining background search to the domain actually used in the text.
  2. Hierarchical P/S/C extraction — parent, sibling, child relations extracted
     in separate slots rather than one flat list.
  3. Analogy validation pass — second LLM call checks T~C holds for S~C,
     pruning hierarchies that are structurally wrong for the context.
  4. Provenance tagging — every output node/edge is tagged:
       concept_origin: "extracted"  (came directly from the source text)
       concept_origin: "inferred_background"  (generated by expansion)
  5. temperature=0 is enforced throughout.

Inputs
------
  --in           Seed concepts JSON  {concepts: [{id, label, chunk_id?, source_text?}]}
                 chunk_id and source_text are populated by the updated select_seed_concepts.py
                 (see note at bottom of file). If source_text is absent the prompt degrades
                 gracefully to concept-only mode.
  --extractions  (optional) Extractions JSON so source paragraphs can be looked up by chunk_id.

Outputs
-------
  --out          Background candidates JSON  {candidates: [...]}
                 Each candidate carries:
                   source_concept, concept_origin, source_context (paragraph used),
                   background_concepts (list),
                   edges [{relation_type, tier, target_concept, justification, confidence}],
                   analogy_check {passed, reason},
                   summary
"""

import argparse
import json
import math
from pathlib import Path
from typing import Any, Dict, List, Literal, Optional, Tuple

from pydantic import BaseModel, Field
from langchain_ollama import ChatOllama


# ---------------------------------------------------------------------------
# Types
# ---------------------------------------------------------------------------

RelationType = Literal[
    "is_a",           # T is a kind of parent P
    "has_part",       # P has part T  (T is component of P)
    "requires_understanding_of",  # understanding T requires knowing target
    "sibling_of",     # T and target share a common parent — same level
    "specializes",    # T is a more specific version of target (child → parent direction)
]

Tier = Literal["parent", "sibling", "child"]


def norm_concept(s: str) -> str:
    return " ".join(str(s).strip().lower().split())


# ---------------------------------------------------------------------------
# Pydantic models
# ---------------------------------------------------------------------------

class HierarchicalEdge(BaseModel):
    tier: Tier = Field(description="Whether this concept is parent (P), sibling (S), or child (C) of T")
    relation_type: RelationType
    target_concept: str
    justification: str
    confidence: float = Field(ge=0.0, le=1.0, default=0.5)


class HierarchicalExpansion(BaseModel):
    source_concept: str
    background_concepts: List[str] = Field(default_factory=list)
    edges: List[HierarchicalEdge] = Field(default_factory=list)
    summary: str = ""


class AnalogyCheck(BaseModel):
    passed: bool
    reason: str
    analogy_score: float = Field(ge=0.0, le=1.0, default=0.5,
                                  description="How well T~C holds for the sibling pair, 0-1")


# ---------------------------------------------------------------------------
# JSON salvage
# ---------------------------------------------------------------------------

def salvage_first_json(s: str) -> str:
    start = s.find("{")
    end = s.rfind("}")
    if start == -1 or end == -1 or end <= start:
        raise ValueError("No JSON object found in model response")
    return s[start:end + 1]


# ---------------------------------------------------------------------------
# Prompt builders
# ---------------------------------------------------------------------------

def make_expansion_prompt(concept: str, source_text: Optional[str]) -> str:
    """
    Context-anchored prompt.  When source_text is provided the LLM sees the
    exact paragraph the concept was extracted from — this is comment 1a from
    the design review and is the single highest-leverage change.
    """
    context_block = ""
    if source_text and source_text.strip():
        context_block = (
            f"\nSOURCE PARAGRAPH (the context in which this concept appears):\n"
            f"\"{source_text.strip()}\"\n"
            "\nAll background concepts you propose MUST be relevant to this specific context, "
            "not to the concept in isolation.\n"
        )

    return (
        "You are expanding a neuroscience knowledge graph with structured background knowledge.\n"
        "Given a source concept and its context, identify prerequisite background concepts "
        "organized as a hierarchy: PARENT concepts more general than T, "
        "SIBLING concepts at the same level as T, and CHILD concepts more specific than T.\n"
        f"{context_block}\n"
        "Return ONLY valid JSON with exactly these keys:\n"
        "source_concept: string\n"
        "background_concepts: list of short noun phrases\n"
        "edges: list of objects, each with:\n"
        "  tier: one of [parent, sibling, child]\n"
        "  relation_type: one of [is_a, has_part, requires_understanding_of, sibling_of, specializes]\n"
        "  target_concept: short noun phrase\n"
        "  justification: short explanation (1 sentence)\n"
        "  confidence: number 0-1\n"
        "summary: short summary string\n\n"
        "Rules:\n"
        "- Concepts must be grounded in the source paragraph context, not generic.\n"
        "- Keep concepts short and specific (2–5 words preferred).\n"
        "- Do NOT include the source concept itself as a target.\n"
        "- Return at most 3 parents, 3 siblings, 3 children (9 edges total max).\n"
        "- If a tier has no good candidates, return an empty list for it.\n"
        "- Confidence below 0.4 means you are unsure — still include it but set confidence low.\n\n"
        f"SOURCE CONCEPT: {concept}\n"
    )


def make_analogy_prompt(
    target_concept: str,
    sibling_concept: str,
    child_concept: str,
    source_text: Optional[str],
) -> str:
    """
    Analogy validation: does 'T is to child_concept as sibling_concept is to child_concept'
    hold in the context of the source paragraph?

    This is the analogy test from comment 2b: T~C should hold for S~C.
    We test whether the proposed child is equally valid as a child of the sibling,
    which would indicate the child is too generic, OR whether the relationship is
    genuinely specific to T.
    """
    ctx = f'\nContext: "{source_text.strip()}"' if source_text and source_text.strip() else ""

    return (
        "You are validating a proposed concept hierarchy for a neuroscience knowledge graph.\n"
        f"{ctx}\n\n"
        f"Proposed hierarchy:\n"
        f"  Target concept (T): {target_concept}\n"
        f"  Sibling concept (S): {sibling_concept}\n"
        f"  Child concept  (C): {child_concept}\n\n"
        "Analogy test: Does 'T is to C' hold in the same way as 'S is to C'?\n"
        "  - If both T and S relate equally to C, C is probably too generic or shared.\n"
        "  - If only T specifically relates to C in this context, the hierarchy is sound.\n"
        "  - If the analogy is completely broken (C has nothing to do with T or S), reject it.\n\n"
        "Return ONLY valid JSON with exactly these keys:\n"
        "passed: boolean — true if the child C is specifically relevant to T (not just generic)\n"
        "reason: short explanation (1 sentence)\n"
        "analogy_score: float 0-1, how specifically C relates to T vs how generically it applies\n"
    )


# ---------------------------------------------------------------------------
# Extraction helpers
# ---------------------------------------------------------------------------

def build_chunk_text_map(extractions_path: Optional[Path]) -> Dict[str, str]:
    """Load chunk_id -> text mapping from extractions JSON if provided."""
    if not extractions_path or not extractions_path.exists():
        return {}
    data = json.loads(extractions_path.read_text(encoding="utf-8"))
    return {
        r["chunk_id"]: r.get("text", "")
        for r in data.get("extractions", [])
        if "chunk_id" in r and not r.get("error")
    }


def run_analogy_check(
    llm: ChatOllama,
    target: str,
    sibling: str,
    child: str,
    source_text: Optional[str],
) -> AnalogyCheck:
    """Run a single analogy check. Returns a safe default on LLM error."""
    try:
        resp = llm.invoke(make_analogy_prompt(target, sibling, child, source_text))
        raw = getattr(resp, "content", str(resp))
        parsed = json.loads(salvage_first_json(raw))
        return AnalogyCheck.model_validate(parsed)
    except Exception as e:
        # Be permissive on analogy errors — don't block the whole row
        return AnalogyCheck(passed=True, reason=f"analogy-check-error: {e}", analogy_score=0.5)


def validate_edges_with_analogy(
    llm: ChatOllama,
    concept: str,
    edges: List[HierarchicalEdge],
    source_text: Optional[str],
) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    """
    For every (sibling, child) pair, run the analogy validation.
    Edges that fail the analogy test get their confidence penalised by 0.3
    (not hard-rejected, so data is preserved for downstream scoring).
    Returns (validated_edge_dicts, analogy_summary).
    """
    siblings = [e for e in edges if e.tier == "sibling"]
    children = [e for e in edges if e.tier == "child"]

    # Build a penalty map: child_concept -> max analogy_score observed
    # (higher analogy_score means C is specific to T, which is good)
    analogy_scores: Dict[str, float] = {}
    analogy_reasons: Dict[str, str] = {}

    for sib in siblings:
        for child in children:
            key = child.target_concept
            check = run_analogy_check(
                llm,
                concept,
                sib.target_concept,
                child.target_concept,
                source_text,
            )
            # Keep the best analogy score across all sibling pairs for this child
            prev = analogy_scores.get(key, 0.0)
            if check.analogy_score > prev:
                analogy_scores[key] = check.analogy_score
                analogy_reasons[key] = check.reason

    out_edges = []
    for e in edges:
        d = e.model_dump()
        # Mark provenance
        d["concept_origin"] = "inferred_background"
        if e.tier == "child" and e.target_concept in analogy_scores:
            score = analogy_scores[e.target_concept]
            d["analogy_score"] = score
            d["analogy_reason"] = analogy_reasons[e.target_concept]
            # Penalise generic children: if score < 0.5, the child applies to siblings too
            if score < 0.5:
                d["confidence"] = max(0.0, float(d["confidence"]) - 0.3)
                d["analogy_flag"] = "generic_child_penalised"
            else:
                d["analogy_flag"] = "specific_to_target"
        else:
            d["analogy_score"] = None
            d["analogy_reason"] = "not_tested"
            d["analogy_flag"] = "no_analogy_test"
        out_edges.append(d)

    summary = {
        "siblings_tested": len(siblings),
        "children_tested": len(children),
        "analogy_pairs_checked": len(siblings) * len(children),
        "children_penalised": sum(
            1 for e in out_edges
            if e.get("analogy_flag") == "generic_child_penalised"
        ),
    }
    return out_edges, summary


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description=(
            "Context-anchored background knowledge expansion with hierarchical P/S/C "
            "extraction and analogy validation. Improved version of expand_background_knowledge.py."
        )
    )
    parser.add_argument("--in", dest="in_path", required=True,
                        help="Input seed concepts JSON {concepts: [{id, label, chunk_id?, source_text?}]}.")
    parser.add_argument("--out", dest="out_path", required=True,
                        help="Output background candidates JSON.")
    parser.add_argument("--extractions", default="",
                        help="Optional: extractions JSON to look up source paragraphs by chunk_id.")
    parser.add_argument("--model", default="llama3.2:3b",
                        help="Ollama model name.")
    parser.add_argument("--limit", type=int, default=0,
                        help="Process only first N concepts (0=all).")
    parser.add_argument("--skip-analogy", action="store_true",
                        help="Skip the analogy validation pass (faster, less accurate).")
    args = parser.parse_args()

    in_path = Path(args.in_path)
    out_path = Path(args.out_path)

    data = json.loads(in_path.read_text(encoding="utf-8"))
    concepts = data.get("concepts", [])
    if args.limit and args.limit > 0:
        concepts = concepts[: args.limit]

    # Build chunk_id -> paragraph lookup
    chunk_text_map = build_chunk_text_map(
        Path(args.extractions) if args.extractions else None
    )

    # temperature=0 enforced — comment 1b
    llm = ChatOllama(model=args.model, temperature=0)

    out: List[Dict[str, Any]] = []
    total = len(concepts)

    for i, row in enumerate(concepts, start=1):
        concept = norm_concept(row.get("id", ""))
        if not concept:
            continue

        # Resolve source text: prefer explicit field, then chunk lookup
        source_text: Optional[str] = row.get("source_text") or None
        if not source_text:
            chunk_id = row.get("chunk_id") or row.get("id")
            source_text = chunk_text_map.get(chunk_id) or None

        try:
            prompt = make_expansion_prompt(concept, source_text)
            resp = llm.invoke(prompt)
            raw = getattr(resp, "content", str(resp))
            raw_json = salvage_first_json(raw)
            parsed = json.loads(raw_json)
            validated = HierarchicalExpansion.model_validate(parsed)

            source_concept = norm_concept(validated.source_concept) or concept

            # Dedup background_concepts
            bg_concepts = sorted(
                {
                    norm_concept(c)
                    for c in validated.background_concepts
                    if norm_concept(c) and norm_concept(c) != source_concept
                }
            )

            # Normalise edges
            edges_raw: List[HierarchicalEdge] = []
            seen = set()
            for e in validated.edges:
                target = norm_concept(e.target_concept)
                if not target or target == source_concept:
                    continue
                key = (e.tier, e.relation_type, target)
                if key in seen:
                    continue
                seen.add(key)
                edges_raw.append(
                    HierarchicalEdge(
                        tier=e.tier,
                        relation_type=e.relation_type,
                        target_concept=target,
                        justification=str(e.justification).strip(),
                        confidence=float(e.confidence),
                    )
                )

            # Analogy validation pass
            if not args.skip_analogy and edges_raw:
                validated_edges, analogy_summary = validate_edges_with_analogy(
                    llm, source_concept, edges_raw, source_text
                )
            else:
                validated_edges = [
                    {
                        **e.model_dump(),
                        "concept_origin": "inferred_background",
                        "analogy_score": None,
                        "analogy_reason": "skipped",
                        "analogy_flag": "skipped",
                    }
                    for e in edges_raw
                ]
                analogy_summary = {"skipped": True}

            out.append(
                {
                    "source_concept": source_concept,
                    # Provenance: this concept came from the extracted document text
                    "concept_origin": "extracted",
                    "source_context": source_text or "",
                    "background_concepts": bg_concepts,
                    "edges": validated_edges,
                    "analogy_summary": analogy_summary,
                    "summary": str(validated.summary).strip(),
                }
            )
            n_edges = len(validated_edges)
            n_penalised = sum(
                1 for e in validated_edges
                if e.get("analogy_flag") == "generic_child_penalised"
            )
            print(
                f"[{i}/{total}] ok concept={source_concept}  "
                f"edges={n_edges}  penalised={n_penalised}"
            )

        except Exception as e:
            out.append({"source_concept": concept, "concept_origin": "extracted", "error": str(e)})
            print(f"[{i}/{total}] ERROR concept={concept} -> {e}")

    out_path.write_text(json.dumps({"candidates": out}, indent=2), encoding="utf-8")
    print(f"\nSaved {len(out)} background candidates to {out_path}")


# ---------------------------------------------------------------------------
# Note on select_seed_concepts.py update
# ---------------------------------------------------------------------------
# To feed source_text into this pipeline without manual annotation, update
# select_seed_concepts.py to also JOIN the Chunk text:
#
#   Q_TOP_CONCEPTS = """
#   MATCH (c:Concept:Entity)
#   OPTIONAL MATCH (ch:Chunk:Entity)-[:MENTIONS]->(c)
#   WITH c, ch, count(ch) AS mention_count
#   ORDER BY mention_count DESC
#   WITH c, collect(ch)[0] AS top_chunk, sum(mention_count) AS total_mentions
#   RETURN c.id AS concept_id,
#          coalesce(c.label, c.id) AS label,
#          total_mentions AS mention_count,
#          top_chunk.id AS chunk_id,
#          top_chunk.text AS source_text
#   ORDER BY total_mentions DESC, concept_id ASC
#   LIMIT $limit
#   """
#
# This surfaces the highest-mention source paragraph for each concept,
# giving the expansion LLM the actual neuroscience context it appeared in.
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    main()